query get_created_credentials($user_id: uuid!) {
  me(where: { credential_groups: { admin_id: { _eq: $user_id } } }) {
    credential_groups {
      admin_id
      category
      description
      id
      image
      name
      slug
      wallets
    }
  }
}
