query get_credential($credential_id: uuid!) {
  credential_group_by_pk(id: $credential_id) {
    admin {
      id
      name
      pfp
    }
    admin_id
    category
    description
    id
    image
    name
    slug
    wallets
  }

  credentials_by_pk(id: $credential_id) {
    name
    attitudes
    ceramic
    created_at
    description
    details
    group_id
    id
    image
    info
    issuer_id
    knowledges
    namespace
    pow
    skills
    status
    target_id
    updated_at
    issuer {
      id
      name
      pfp
    }
    target {
      name
    }
  }
}
