query get_credential_group_info($credentialId: uuid!) {
  credential_group_by_pk(id: $credentialId) {
    admin {
      name
      pfp
    }
    admin_id
    category
    description
    id
    image
    name
    slug
    wallets
  }
}

query get_credential_group_info_by_slug($slug: String!) {
  credential_group(where: {slug: {_eq: $slug}}) {
    admin {
      name
      pfp
    }
    admin_id
    category
    description
    id
    image
    name
    slug
    wallets
  }
}
